"""add_guest_name_and_guest_phone

Revision ID: 01570c470e4a
Revises: e7c75bd4b402
Create Date: 2026-03-02 14:28:00.020096

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '01570c470e4a'
down_revision = 'e7c75bd4b402'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Použije sa pri `alembic upgrade ...`."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('guest_name', sa.String(length=100), nullable=True))
    op.add_column('reservations', sa.Column('guest_phone', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Použije sa pri `alembic downgrade ...`."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservations', 'guest_phone')
    op.drop_column('reservations', 'guest_name')
    # ### end Alembic commands ###
