"""overview_highlights

Revision ID: 042008e5450f
Revises: 85b9bbe77e14
Create Date: 2026-04-06 15:35:56.886142

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '042008e5450f'
down_revision = '85b9bbe77e14'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Použije sa pri `alembic upgrade ...`."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('overview_text', sa.Text(), nullable=True))
    op.add_column('restaurants', sa.Column('highlights', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Použije sa pri `alembic downgrade ...`."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'highlights')
    op.drop_column('restaurants', 'overview_text')
    # ### end Alembic commands ###
