"""add_gallery_images

Revision ID: 14b2fb9e8b94
Revises: c7407efdcaf9
Create Date: 2026-03-08 20:11:36.830515

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '14b2fb9e8b94'
down_revision = 'c7407efdcaf9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Použije sa pri `alembic upgrade ...`."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('gallery_images', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Použije sa pri `alembic downgrade ...`."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'gallery_images')
    # ### end Alembic commands ###
