"""add_favorite_restaurant

Revision ID: 3f8555b31053
Revises: 14b2fb9e8b94
Create Date: 2026-03-12 16:27:20.960927

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '3f8555b31053'
down_revision = '14b2fb9e8b94'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Použije sa pri `alembic upgrade ...`."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'restaurant_id'),
    sa.UniqueConstraint('user_id', 'restaurant_id', name='uq_user_restaurant_favorite')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Použije sa pri `alembic downgrade ...`."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    # ### end Alembic commands ###
