"""split_for_restaurants_table

Revision ID: 6fdd866b54c7
Revises: 042008e5450f
Create Date: 2026-04-14 23:33:50.693558

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6fdd866b54c7'
down_revision = '042008e5450f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Použije sa pri `alembic upgrade ...`."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faq_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=500), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('menu_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('restaurant_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('dining_style', sa.String(length=100), nullable=True),
    sa.Column('dress_code', sa.String(length=100), nullable=True),
    sa.Column('parking_details', sa.String(length=200), nullable=True),
    sa.Column('payment_options', sa.String(length=500), nullable=True),
    sa.Column('neighborhood', sa.String(length=100), nullable=True),
    sa.Column('cross_street', sa.String(length=100), nullable=True),
    sa.Column('executive_chef', sa.String(length=100), nullable=True),
    sa.Column('public_transit', sa.String(length=200), nullable=True),
    sa.Column('delivery_takeout', sa.String(length=200), nullable=True),
    sa.Column('catering_info', sa.Text(), nullable=True),
    sa.Column('private_party_info', sa.Text(), nullable=True),
    sa.Column('additional_info', sa.Text(), nullable=True),
    sa.Column('overview_text', sa.Text(), nullable=True),
    sa.Column('highlights', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('restaurant_id')
    )
    op.create_table('restaurant_hours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.String(length=10), nullable=False),
    sa.Column('open_time', sa.Time(), nullable=True),
    sa.Column('close_time', sa.Time(), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('restaurant_id', 'day_of_week')
    )
    op.create_table('menu_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('price', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['menu_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('restaurants', 'payment_options')
    op.drop_column('restaurants', 'delivery_takeout')
    op.drop_column('restaurants', 'parking_details')
    op.drop_column('restaurants', 'overview_text')
    op.drop_column('restaurants', 'website')
    op.drop_column('restaurants', 'dining_style')
    op.drop_column('restaurants', 'neighborhood')
    op.drop_column('restaurants', 'cross_street')
    op.drop_column('restaurants', 'faqs')
    op.drop_column('restaurants', 'opening_hours')
    op.drop_column('restaurants', 'private_party_info')
    op.drop_column('restaurants', 'highlights')
    op.drop_column('restaurants', 'catering_info')
    op.drop_column('restaurants', 'additional_info')
    op.drop_column('restaurants', 'executive_chef')
    op.drop_column('restaurants', 'menu')
    op.drop_column('restaurants', 'dress_code')
    op.drop_column('restaurants', 'public_transit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Použije sa pri `alembic downgrade ...`."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('public_transit', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('restaurants', sa.Column('dress_code', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('restaurants', sa.Column('menu', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True))
    op.add_column('restaurants', sa.Column('executive_chef', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('restaurants', sa.Column('additional_info', mysql.TEXT(), nullable=True))
    op.add_column('restaurants', sa.Column('catering_info', mysql.TEXT(), nullable=True))
    op.add_column('restaurants', sa.Column('highlights', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True))
    op.add_column('restaurants', sa.Column('private_party_info', mysql.TEXT(), nullable=True))
    op.add_column('restaurants', sa.Column('opening_hours', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True))
    op.add_column('restaurants', sa.Column('faqs', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True))
    op.add_column('restaurants', sa.Column('cross_street', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('restaurants', sa.Column('neighborhood', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('restaurants', sa.Column('dining_style', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('restaurants', sa.Column('website', mysql.VARCHAR(length=500), nullable=True))
    op.add_column('restaurants', sa.Column('overview_text', mysql.TEXT(), nullable=True))
    op.add_column('restaurants', sa.Column('parking_details', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('restaurants', sa.Column('delivery_takeout', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('restaurants', sa.Column('payment_options', mysql.VARCHAR(length=500), nullable=True))
    op.drop_table('menu_items')
    op.drop_table('restaurant_hours')
    op.drop_table('restaurant_details')
    op.drop_table('menu_categories')
    op.drop_table('faq_items')
    # ### end Alembic commands ###
