"""menu_details_faq

Revision ID: 85b9bbe77e14
Revises: ad91327d6a48
Create Date: 2026-04-06 14:49:51.536412

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '85b9bbe77e14'
down_revision = 'ad91327d6a48'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Použije sa pri `alembic upgrade ...`."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('website', sa.String(length=500), nullable=True))
    op.add_column('restaurants', sa.Column('dining_style', sa.String(length=100), nullable=True))
    op.add_column('restaurants', sa.Column('dress_code', sa.String(length=100), nullable=True))
    op.add_column('restaurants', sa.Column('parking_details', sa.String(length=200), nullable=True))
    op.add_column('restaurants', sa.Column('payment_options', sa.String(length=500), nullable=True))
    op.add_column('restaurants', sa.Column('neighborhood', sa.String(length=100), nullable=True))
    op.add_column('restaurants', sa.Column('cross_street', sa.String(length=100), nullable=True))
    op.add_column('restaurants', sa.Column('executive_chef', sa.String(length=100), nullable=True))
    op.add_column('restaurants', sa.Column('public_transit', sa.String(length=200), nullable=True))
    op.add_column('restaurants', sa.Column('catering_info', sa.Text(), nullable=True))
    op.add_column('restaurants', sa.Column('private_party_info', sa.Text(), nullable=True))
    op.add_column('restaurants', sa.Column('additional_info', sa.Text(), nullable=True))
    op.add_column('restaurants', sa.Column('delivery_takeout', sa.String(length=200), nullable=True))
    op.add_column('restaurants', sa.Column('menu', sa.JSON(), nullable=True))
    op.add_column('restaurants', sa.Column('faqs', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Použije sa pri `alembic downgrade ...`."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'faqs')
    op.drop_column('restaurants', 'menu')
    op.drop_column('restaurants', 'delivery_takeout')
    op.drop_column('restaurants', 'additional_info')
    op.drop_column('restaurants', 'private_party_info')
    op.drop_column('restaurants', 'catering_info')
    op.drop_column('restaurants', 'public_transit')
    op.drop_column('restaurants', 'executive_chef')
    op.drop_column('restaurants', 'cross_street')
    op.drop_column('restaurants', 'neighborhood')
    op.drop_column('restaurants', 'payment_options')
    op.drop_column('restaurants', 'parking_details')
    op.drop_column('restaurants', 'dress_code')
    op.drop_column('restaurants', 'dining_style')
    op.drop_column('restaurants', 'website')
    # ### end Alembic commands ###
