"""payment

Revision ID: ad91327d6a48
Revises: f94edf4be2e4
Create Date: 2026-03-19 18:38:24.563437

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'ad91327d6a48'
down_revision = 'f94edf4be2e4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Použije sa pri `alembic upgrade ...`."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('stripe_session_id', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_reservation_id'), 'payments', ['reservation_id'], unique=True)
    op.create_index(op.f('ix_payments_stripe_session_id'), 'payments', ['stripe_session_id'], unique=True)
    op.add_column('restaurants', sa.Column('reservation_fee', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Použije sa pri `alembic downgrade ...`."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'reservation_fee')
    op.drop_index(op.f('ix_payments_stripe_session_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_reservation_id'), table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
