"""add_opening_hours_to_restaurant

Revision ID: dcbf19c21f1a
Revises: 01570c470e4a
Create Date: 2026-03-08 15:05:11.320912

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'dcbf19c21f1a'
down_revision = '01570c470e4a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Použije sa pri `alembic upgrade ...`."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('opening_hours', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Použije sa pri `alembic downgrade ...`."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'opening_hours')
    # ### end Alembic commands ###
