"""add_max_capacity

Revision ID: e7c75bd4b402
Revises: c0b6d44b025d
Create Date: 2026-03-02 13:48:15.409858

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'e7c75bd4b402'
down_revision = 'c0b6d44b025d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Použije sa pri `alembic upgrade ...`."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('max_capacity', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Použije sa pri `alembic downgrade ...`."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'max_capacity')
    # ### end Alembic commands ###
