"""restaurant_tables

Revision ID: f94edf4be2e4
Revises: 3f8555b31053
Create Date: 2026-03-16 22:40:40.917047

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'f94edf4be2e4'
down_revision = '3f8555b31053'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Použije sa pri `alembic upgrade ...`."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant_tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('table_number', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('restaurant_id', 'table_number')
    )
    op.create_index(op.f('ix_restaurant_tables_restaurant_id'), 'restaurant_tables', ['restaurant_id'], unique=False)
    op.add_column('reservations', sa.Column('table_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_reservations_table_id'), 'reservations', ['table_id'], unique=False)
    op.create_foreign_key(None, 'reservations', 'restaurant_tables', ['table_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Použije sa pri `alembic downgrade ...`."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reservations', type_='foreignkey')
    op.drop_index(op.f('ix_reservations_table_id'), table_name='reservations')
    op.drop_column('reservations', 'table_id')
    op.drop_index(op.f('ix_restaurant_tables_restaurant_id'), table_name='restaurant_tables')
    op.drop_table('restaurant_tables')
    # ### end Alembic commands ###
